### ISSUE TITLE
Cannot open load file, no such file or directory, pallet

### ISSUE THREAD

**Issue by rajeshponnala** [pervezfunctor/emacs.d#1]
1) installed cask successfully

2) Loading error:
Warning (initialization): An error occurred while loading `/home/rajesh/.emacs.d/init.el':

File error: Cannot open load file, no such file or directory, pallet

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.

3) emacs --debug-init

error-message:

Debugger entered--Lisp error: (file-error "Cannot open load file" "no such file or directory" "pallet")
  require(pallet)
  eval-buffer(#<buffer  *load*-134983> nil "/home/rajesh/.emacs.d/lisp/init-elpa.el" nil t)  ; Reading at buffer position 178
  load-with-code-conversion("/home/rajesh/.emacs.d/lisp/init-elpa.el" "/home/rajesh/.emacs.d/lisp/init-elpa.el" nil t)
  require(init-elpa)
  eval-buffer(#<buffer  *load*> nil "/home/rajesh/.emacs.d/init.el" nil t)  ; Reading at buffer position 442
  load-with-code-conversion("/home/rajesh/.emacs.d/init.el" "/home/rajesh/.emacs.d/init.el" t t)
  load("/home/rajesh/.emacs.d/init" t t)
  #[0 "\205\262	\306=\203\307\310Q\202;	\311=\204\307\312Q\202;\313\307\314\315#\203*\316\202;\313\307\314\317#\203:\320\nB\321\202;\316\322\323\322\211#\210\322=\203a\324\325\326\307\327Q!\"\323\322\211#\210\322=\203`\210\203\243\330!\331\232\203\243\332!\211\333P\334!\203}\211\202\210\334!\203\207\202\210\314\262\203\241\335\"\203\237\336\337#\210\340\341!\210\266\f?\205\260\314\323\342\322\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" (initialization "`_emacs' init file is deprecated, please use `.emacs'") "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7 "\n\n(fn)"]()
  command-line()
  normal-top-level()

**Comment by pervezfunctor** [comment]
You need to install [cask](http://cask.readthedocs.org/en/latest/guide/installation.html) and then run cask install in your .emacs.d folder

**Comment by rajeshponnala** [comment]
done sir :)
